version: '3.7'

services:

  sample:
    container_name: react_test
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3002:80
    environment:
      - CHOKIDAR_USEPOLLING=true
