import { IServerResponse } from '../Interface';

const mockData :IServerResponse = {
  bonuses: [{
    id: 1,
    title: 'Sitecostructor.io',
    description: 'Site constructor',
    link: 'https://sitecostructor.io/?p=itpaycodes',
    promocode: 'itpaycodes',
    isUsed: false,
  },
  {
    id: 166,
    title: 'Appvision.com',
    description: 'SDK',
    link: 'http://appvision.com/+itpaycodes',
    promocode: 'itpaycodes',
    isUsed: false,
  },
  {
    id: 155,
    title: 'Analytics.com',
    description: 'Analytics',
    link: 'https://www.analytics.com/?ref=itpaycodes',
    promocode: 'itpaycodes',
    isUsed: false,
  },
  {
    id: 122,
    title: 'Logotype',
    description: 'Logos',
    link: 'https://www.logotype.design/',
    promocode: 'itpaycodes',
    isUsed: false,
  },
  {
    id: 133,
    title: 'Certificates',
    description: 'SSL',
    link: 'https://www.certificates.com/ssl-certificate/',
    promocode: 'itpaycodes',
    isUsed: false,
  },
  {
    id: 1444,
    title: 'Seorank.com',
    description: 'SEO',
    link: 'https://seorank.com/',
    promocode: 'itpaycodes',
    isUsed: false,
  },
  {
    id: 1112,
    title: 'marke.com',
    description: 'Marketing',
    link: 'http://marketing.com/',
    promocode: 'itpaycodes',
    isUsed: false,
  },
  {
    id: 101,
    title: 'Major.com',
    description: 'Hosting',
    link: 'https://www.hosting.com/',
    promocode: 'itpaycodes',
    isUsed: false,
  },
  {
    id: 198,
    title: 'Setup.com',
    description: 'Web sites',
    link: 'http://www.setup.com/instructions/promocode',
    promocode: 'itpaycodes',
    isUsed: false,
  },
  {
    id: 189,
    title: 'topvisor.com',
    description: 'Analytics',
    link: 'https://topvisor.com/promo/itpaycodes/',
    promocode: 'itpaycodes',
    isUsed: false,
  },
  {
    id: 18,
    title: 'seopult.com',
    description: 'SEO',
    link: 'https://promopult.com/',
    promocode: 'itpaycodes',
    isUsed: false,
  },
  {
    id: 17,
    title: 'sendpulse.com',
    description: 'Emails',
    link: 'https://sendpulse.com/',
    promocode: 'itpaycodes',
    isUsed: false,
  },
  {
    id: 156,
    title: 'Turbotext.com',
    description: 'Content marketing',
    link: 'http://turbotext.com/',
    promocode: 'itpaycodes',
    isUsed: false,
  },
  {
    id: 14,
    title: 'Witget.com',
    description: 'Widgets',
    link: 'https://witget.com/?partner=itpaycodes',
    promocode: 'itpaycodes',
    isUsed: false,
  },
  {
    id: 145,
    title: 'Spywords.com',
    description: 'Analytics',
    link: 'http://spywords.com',
    promocode: 'itpaycodes',
    isUsed: false,
  },
  {
    id: 1456,
    title: 'Etxt.com',
    description: 'Content Marketing',
    link: 'https://www.etxt.com/',
    promocode: 'itpaycodes',
    isUsed: false,
  },
  {
    id: 13,
    title: 'Serpstat.com',
    description: 'Analytics',
    link: 'https://analytics.com',
    promocode: 'itpaycodes',
    isUsed: false,
  },
  {
    id: 12,
    title: 'webhost.com',
    description: 'Hosting',
    link: 'https://webhost.com/',
    promocode: 'itpaycodes',
    isUsed: false,
  },
  {
    id: 123,
    title: 'Unisender.com',
    description: 'Email marketing',
    link: 'https://www.unisender.com',
    promocode: 'itpaycodes',
    isUsed: false,
  },
  {
    id: 1123,
    title: 'getuniq.com',
    description: 'Advertisment',
    link: 'http://itpaycodes.getuniq.com',
    promocode: 'itpaycodes',
    isUsed: false,
  },
  ],
  header: {
    balance: 213920,
    next_payout: 159465,
    currency: 'usd',
  },
};

export default mockData;
