export const SAVE_DATA = 'SAVE_DATA';
export const BONUSES_LOADING = 'BONUSES_LOADING';
export const CHANGE_BONUS = 'CHANGE_BONUS';
export const POST_ACTIVATE_BONUS = 'POST_ACTIVATE_BONUS';
export const POST_FILTER_BONUS = 'POST_FILTER_BONUS';
